apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipruler-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ipruler-agent
  template:
    metadata:
      labels:
        app: ipruler-agent
    spec:
      hostNetwork: true
      containers:
      - name: ipruler
        image: plutocholia/ipruler:v0.1.0
        imagePullPolicy: "Always"
        env:
        - name: MODE
          value: "api"
        # - name: ENABLE_PERSISTENCE
        #   value: "true"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        # volumeMounts:
        # - name: host-network-dispatcher
        #   mountPath: /etc/networkd-dispatcher/routable.d
      # volumes:
      # - name: host-network-dispatcher
      #   hostPath:
      #     path: /etc/networkd-dispatcher/routable.d
      #     type: Directory
