stages:
- publish-image

include:
  - component: git.tapsell.ir/components/autodevops/docker-build-publish@1
    inputs:
      job_name: docker-build-publish
      rules:
        - if: $CI_COMMIT_BRANCH == "master"
          when: on_success
        - when: never
      extra_args: '--build-arg="GO_VERSION=1.22.4" --build-arg="GOARCH=amd64" --build-arg="BASE_IMAGE=ubuntu:22.04"'
