agent-config:
  mode: api
  config-reload-duration-seconds: 15
  enable-persistence: false

image:
  repository: plutocholia/ipruler-agent
  tag: ~
  pullPolicy: IfNotPresent

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 256Mi
  # requests:
  #   cpu: 250m
  #   memory: 128Mi

# ipruler-config:
#   rules:
#   - from: 172.31.201.12/32
#     table: 102
