apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      hostNetwork: true
      containers:
      - name: ubuntu
        image: ubuntu:22.04
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: host-network-dispatcher
          mountPath: /etc/networkd-dispatcher/routable.d/
        - name: host-var-run
          mountPath: /var/run
      volumes:
      - name: host-network-dispatcher
        hostPath:
          path: /etc/networkd-dispatcher/routable.d/
          type: Directory
      - name: host-var-run
        hostPath:
          path: /var/run
          type: Directory

