settings:
  table-hard-sync:
  - 102
  - 103
rules:
- from: 172.31.201.11/32
  table: 102
- from: 172.31.201.12/32
  table: 102
# - sourceIP: 172.31.201.13/32
#   table: 103
routes:
- to: default
  via: 172.31.201.1
  table: 102
  protocol: static
  flag: onlink
## below example won't work!
# - to: 172.31.201.3/32
#   via: 172.31.201.1
#   table: 102
#   protocol: static
#   flag: onlink
#   scope: link